### ISSUE TITLE
Error when running "npm start"

### ISSUE THREAD

**Issue by RabbleMonster** [supnate/rekit#121]
I've followed the instructions for using rekit under Usage on the code tab.  "npm install" ran with no errors, but "npm start" gives me the error below  

Things I've tried:
Creating a new app and using "yarn install" and "yarn start"
Deleting the ")" from the action.js file.  The parentheses were all correct but I tried it anyways.  
Ran a cmd as administrator and went through the process of creating an app again

I'm on windows 10 and my version of npm is 6.0.0

Any help would be great.  Thanks!

    \node_modules\rekit-core\core\action.js:115
      ));
      ^

    SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\John\TSS_FRONT_TEST\TSS_FRONT\node_modules\rekit-core\core\index.js:50:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! TSS_FRONT@0.1.0 start: `node scripts/start.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the TSS_FRONT@0.1.0 start script.

**Comment by RabbleMonster** [comment]
I figured it out, there's a comma before the parentheses that shouldn't be there.  I deleted it and it's working fine now.

**Comment by supnate** [comment]
Interesting, there should be no syntax error in rekit-core files. I can't reproduce the issue. Did you accidentally change the file?

**Comment by RabbleMonster** [comment]
Not until I got the syntax error.  I'll create another app and see if it happens again.

**Comment by RabbleMonster** [comment]
Same thing happened.  Deleting the comma on line 114 of action.js fixed it.

**Comment by supnate** [comment]
Thanks @RabbleMonster for finding this! Just realized trailing commas in functions were only supported from version 8. I have published a new rekit core v2.3.2 to support lower nodejs.
