### ISSUE TITLE
rekit-core error

### ISSUE THREAD

**Issue by zhangpengdeshu** [supnate/rekit#141]
module.js:540
    throw err;
Error: Cannot find module 'rekit-core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getLocalRekitCore (/usr/local/lib/node_modules/rekit/bin/rekit.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/rekit/bin/rekit.js:43:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by sam019** [comment]
same issue;  expect solution

**Comment by sam019** [comment]
i resolve this problem via degrade rekit vesion to 2.0.7 :)

**Comment by mrtrunin** [comment]
Highlighting that this is still a very relevant issue.

$ rekit
module.js:549
    throw err;
    ^

Error: Cannot find module 'rekit-core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getLocalRekitCore (/usr/local/lib/node_modules/rekit/bin/rekit.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/rekit/bin/rekit.js:43:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)


Degrating rekit to 2.0.7 has worked for me too.

**Comment by mrtrunin** [comment]
After a bit of trial and error, it looks like the last stable version from this issue's point of view is 2.3.0. So downgrading to 2.3.0 should do the trick.

**Comment by supnate** [comment]
It now fixed in rekit@2.3.3 . Sorry for the late fix since it works in Rekit Studio. I just realized this is a command line issue. Thanks all for the information!
