### ISSUE TITLE
rekit create app fails behind proxy

### ISSUE THREAD

**Issue by sripadkollur** [supnate/rekit#193]
I installed latest version of rekit. My PC is behind proxy and http_proxy https_proxy environment variables are set properly, but the "rekit create app" command fails with following error.
If I run the same command on PC not behind proxy then this command works fine.

$ rekit -v
3.0.0-beta.3
$ rekit-studio -v
3.0.0-beta.2

$ rekit create rekit-app2
Creating app:  Namespace { commandName: 'create', name: 'rekit-app2' }
Looking for the git repo for app type rekit-react...
Failed to get last commit of app registry:  { Error: connect ETIMEDOUT 192.30.253.116:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.116',
  port: 443 }
Failed to get app types:  FAILED_CHECK_APP_REGISTRY_LATEST_COMMIT
(node:6808) UnhandledPromiseRejectionWarning: GET_APP_TYPES_FAILED
(node:6808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or
by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.

**Comment by Purus** [comment]
I can confirm on the same. Proxy details are already set in .npmrc file too. But behind proxy app creating is not working. It's a kind of blocker as I can't try the studio.
