### ISSUE TITLE
can't create app

### ISSUE THREAD

**Issue by hermaproditus** [supnate/rekit#57]
when i create a rekit app:
`rekit create myapp --sass`

error show:
```
Welcome to Rekit, now creating your project...
Copying files...
Getting the latest dependencies versions...
(node:3874) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Failed to get dependencies. The project was not created. Please check and retry.
{ Error: connect ETIMEDOUT 151.101.73.147:443
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '151.101.73.147',
  port: 443 }
```

**Comment by supnate** [comment]
Please check if you can access internet from command line.
